version: '2'

services:
    master:
        image: ros:melodic-ros-core
        command: roscore
        container_name: master
        environment:
            - ROS_HOSTNAME = master
            - ROS_MASTER_URI=http://master:11311
        networks:
            - ros_net

    mavros:
        image: rezenders/mavros
        command: roslaunch launch/apm.launch fcu_url:="udp://:14551@:14557"
        container_name: mavros
        environment:
            - ROS_HOSTNAME = mavros
            - ROS_MASTER_URI=http://master:11311
        networks:
            - ros_net
        ports:
            - "14551:14551/udp"
        depends_on:
            - master

    comm:
        build:
            context: rescuer/comm/
        container_name: comm
        environment:
            - ROS_HOSTNAME = comm
            - ROS_MASTER_URI=http://master:11311
        networks:
            - ros_net
        labels:
            io.balena.features.balena-socket: '1'
            io.balena.features.dbus: '1'
        ports:
            - "1024:1024/udp"
        depends_on:
            - master
            - mavros
        command: python comm.py

    hwbridge:
        build:
            context: rescuer/HwBridge/
        command: python hw_bridge.py
        container_name: hwbridge
        environment:
            - ROS_HOSTNAME = hwbridge
            - ROS_MASTER_URI=http://master:11311
        networks:
            - ros_net
        depends_on:
            - master
            - comm
            - mavros

    jason:
        build:
            context: rescuer/JasonAgent/
        command: gradle
        container_name: jason
        environment:
            - ROS_HOSTNAME = jason
            - ROS_MASTER_URI=http://master:11311
        networks:
            - ros_net
        labels:
            io.balena.update.strategy: kill-then-download
        depends_on:
            - master
            - comm
            - hwbridge
            - mavros
        expose:
            - "3272"
        ports:
            - "3272:3272"
    # python:
    #     build:
    #         context: PythonAgent/
    #     command: python droneB.py
    #     container_name: python
    #     environment:
    #         - ROS_HOSTNAME = python
    #         - ROS_MASTER_URI=http://master:11311
    #     networks:
    #         - ros_net
    #     labels:
    #         io.balena.update.strategy: kill-then-download
    #     depends_on:
    #         - master
    #         - comm
    #         - hwbridge
    #         - mavros
networks:
    ros_net:
